name: NightCrawler Agent

on:
  schedule:
    # Her saat başında çalıştır (IST/GMT farkına göre ayarlayabilirsin)
    - cron: '0 * * * *'
  workflow_dispatch: # Manuel çalıştırmaya da izin ver

jobs:
  run-nightcrawler:
    runs-on: ubuntu-latest
    environment: NightCrawler
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Depoyu kopyala
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Gereken Paketleri Kur
        run: pip install -r requirements.txt

      # Chrome ve sürücüsünü indir
      - name: Chrome'u indir
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      # Chromedriver (Selenium için)
      - name: ChromeDriver İndir
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip"
          unzip /tmp/chromedriver.zip -d /tmp
          sudo mv /tmp/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # Main Python scriptini çalıştır
      - name: NightCrawler ajanını başlat
        run: python nightcrawler.py
